package exceptionsExercise2

import atomictest.capture
import atomictest.eq

fun abort(s: String) {}

fun main() {
  TODO()
}